project:
  type: website
  output-dir: docs
  
website:
  title: "Nischal Bhandari"

  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Readings"
        href: readings.qmd
      - text: "Thoughts"
        href: blogs.qmd
      - text: "Reach Out"
        href: reach-out.qmd
    
  page-footer:
    left: "..."

format:
  html:
    css: styles.css
    