project:
  type: website


website:
  title: "Nischal Bhandari"

  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects
      - text: "Readings"
        href: readings.qmd
      - text: "Blog"
        href: blog
    
  page-footer:
    left: "NAN"

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css