---
page-layout: full
title-block-banner: true
---

**Hello, Welcome to my portfolio.**

*My goal here is to keep track of what I am doing and to compile things for my own reference. If any of these things can be of your help, it's my pleasure.*

\

<!-- [Resume](https://1nishbh.github.io/resume/){target="_blank"} -->


\

## Projects

\

### [.. ...](https://github.com/1nishbh/novel.git){target="_blank"}
\

<h3>
  <a href="#" id="unlock-obhano">
    ओभानो
  </a>

  <a href="https://1nishbh.github.io/-/#/title-slide"
     id="obhano-link"
     target="_blank"
     style="display:none; margin-left: 0.5rem;">
    ओभानो
  </a>
</h3>



### [Where are We Going? Tracing the Ever-Evolving Tale of Human Migration](https://1nishbh.github.io/Migration-Our-Story-as-a-Mobile-Species/blog.html){target="_blank"}


<script>
  (function () {
    const password = "ninetesting321";
    const unlockBtn = document.getElementById("unlock-obhano");
    const realLink = document.getElementById("obhano-link");

    if (!unlockBtn || !realLink) return;

    // If already unlocked this session
    if (sessionStorage.getItem("obhanoUnlocked") === "true") {
      unlockBtn.style.display = "none";
      realLink.style.display = "inline";
      return;
    }

    unlockBtn.addEventListener("click", function (e) {
      e.preventDefault();
      const input = prompt("Password:");

      if (input === password) {
        sessionStorage.setItem("obhanoUnlocked", "true");
        unlockBtn.style.display = "none";
        realLink.style.display = "inline";
      } else if (input !== null) {
        alert("Incorrect password");
      }
    });
  })();
</script>

